### ISSUE TITLE
organizations:RemoveAccountFromOrganization unusable

### ISSUE THREAD

**Issue by 0xdabbad00** [aws-samples/aws-iam-permissions-guardrails#4]
The action organizations:RemoveAccountFromOrganization can only be performed by the organization master account.
SCPs do not apply to the Organization Master account.
Therefore this line in the SCP is misleading as it will not protect anything.

https://github.com/aws-samples/aws-iam-permissions-guardrails/blob/114d9b4399180199c8ff501b78c9c116ddf8e146/guardrails/organizations/SCP-ORGANIZATIONS-1.json#L25

**Comment by 0xjjoyy** [comment]
Thanks. Updated https://github.com/aws-samples/aws-iam-permissions-guardrails/commit/fbf734eaa7e7d626e4d097b74a9de3d6cb4ca6cd
