### ISSUE TITLE
Invalid privilege s3:HeadBucket

### ISSUE THREAD

**Issue by 0xdabbad00** [aws-samples/aws-iam-permissions-guardrails#5]
This privilege does not exist: https://github.com/aws-samples/aws-iam-permissions-guardrails/blob/73aee3463a16d8b4a6cd359bfa8de9cfce25d449/guardrails/s3/SCP-S3-5.json#L49

**Comment by 0xjjoyy** [comment]
Thanks. Updated https://github.com/aws-samples/aws-iam-permissions-guardrails/commit/b27d63bf4b7e4ba3c70d9da3f14602c4a2e45fe1
